GET http://localhost:8080/beasts
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/beasts/62
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/beasts?location=Monde%20entier
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/beasts?category=XX
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/beasts?location=Monde%20entier&category=XX
Accept: */*
Cache-Control: no-cache

###

POST http://localhost:8080/beasts/
Content-Type: application/json

{
  "nom": "Thomas Sauvage",
  "apparition": "Harry Potter 8",
  "description": "Thomas code php sauvage"
}

###

PATCH http://localhost:8080/beasts/62
Content-Type: application/json

{
"nom": "Victor Sauvages"
}

###

DELETE http://localhost:8080/beasts/62

###